spring:
    application:
        name: xfl_cv
    thymeleaf:
        cache: false
    cache:
        type: jcache
        jcache:
            config: classpath:cc/xfl12345/person/cv/conf/ehcache.xml
    datasource:
        username: ${spring.application.name}
        password: ${spring.application.name}
        url: "jdbc:mysql://localhost:3306/${spring.application.name}?characterEncoding=utf8&characterSetResults=utf8&serverTimezone=${spring.jackson.time-zone}&allowMultiQueries=true&nullCatalogMeansCurrent=true&useInformationSchema=true&remarks=true"
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
            auto-commit: true
            connection-timeout: 60000
            connection-test-query: SELECT 1
            minimum-idle: 5
            maximum-pool-size: 50
    sql:
        init:
            encoding: UTF-8
    jackson:
        property-naming-strategy: LOWER_CAMEL_CASE
        time-zone: Asia/Hong_Kong
        default-property-inclusion: non_null
        serialization:
            write-date-keys-as-timestamps: false
    servlet:
        multipart:
            max-file-size: -1
    mvc:
        converters:
            preferred-json-mapper: jackson
        contentnegotiation:
            favor-parameter: true
    data:
        rest:
            default-media-type: application/json


server:
    port: 8880
    tomcat:
        accesslog:
            enabled: true
            encoding: UTF-8
            ipv6-canonical: true
        remoteip:
            protocol-header: X-Forwarded-Proto
        use-relative-redirects: true
    servlet:
        encoding:
            enabled: true
            charset: UTF-8
            force-response: true
    forward-headers-strategy: native
    http2:
        enabled: true


logging:
    config: classpath:cc/xfl12345/person/cv/conf/logback-spring.xml
    charset:
        file: UTF-8
    file:
        name: ${spring.application.name}

bucket4j:
    enabled: true
    cache-to-use: jcache


bee:
    osql:
        moreTable:
            columnListWithStar: false
        notCatchModifyDuplicateException: true
        showSQL: true
        showSql:
            showType: true
            showExecutableSql: true
            donotPrintCurrentDate: false


############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
    # token名称 (同时也是cookie名称)
    token-name: ${spring.application.name}
    # token有效期，单位s 默认30天, -1代表永不过期
    timeout: 2592000
    # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
    activity-timeout: -1
    # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
    is-concurrent: false
    # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
    is-share: false
    # token风格
    token-style: uuid
    # 是否输出操作日志
    is-log: true


app:
    sms:
        xfl12345:
            access-key-secret: 'just-test_https://github.com/xfl12345/java-curriculum-vitae-server-web'
            validation-code-length: 6
            expiration-in-minute: 15
            template: 您的验证码是 %s 。（共%s位，%s分钟内有效。切勿将验证码泄漏于他人，如非本人操作请忽略）

